from django.db import models

class SystemConfig(models.Model):
    driver_per_day_price = models.DecimalField(max_digits=10, decimal_places=2, default=20000.00, help_text="Price for booking a driver per day")
    cost_per_km = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, help_text="Cost per kilometer")
    driver_only_cost_per_km = models.DecimalField(max_digits=10, decimal_places=2, default=150.00, help_text="Cost per kilometer for driver-only trips")
    choose_driver_fee_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=20.00, help_text="Fee percentage charged to passenger for manually choosing a driver")
    platform_commission_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=28.00, help_text="Percentage commission platform takes from bookings/trips")
    total_revenue = models.DecimalField(max_digits=15, decimal_places=2, default=0.00, help_text="Total revenue generated by the platform")
    gross_income = models.DecimalField(max_digits=15, decimal_places=2, default=0.00, help_text="Total volume of all transactions")
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'system_configs'
        verbose_name = 'System Configuration'
        verbose_name_plural = 'System Configurations'

    def __str__(self):
        return f"System Pricing Configuration"
