# Generated by Django 6.0.6 on 2026-06-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=100)),
                ('features', models.JSONField(default=list)),
                ('place', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'explore',
            },
        ),
    ]
