# Generated by Django 6.0.6 on 2026-06-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0002_explore'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='explore',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
