# Generated by Django 6.0.6 on 2026-07-01 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0003_explore_category_explore_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('vehicle_make_color', models.CharField(max_length=255)),
                ('plate_number', models.CharField(max_length=50)),
                ('driving_license', models.FileField(blank=True, null=True, upload_to='driver_documents/licenses/')),
                ('government_id', models.FileField(blank=True, null=True, upload_to='driver_documents/ids/')),
                ('home_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home_latitude', models.FloatField(blank=True, null=True)),
                ('home_longitude', models.FloatField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approved_drivers',
            },
        ),
    ]
