# Generated by Django 6.0.6 on 2026-07-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0004_approveddriver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApprovedDriver',
            new_name='Driver',
        ),
        migrations.AlterModelTable(
            name='driver',
            table='drivers',
        ),
    ]
