# Generated by Django 6.0.6 on 2026-07-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0006_driverlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per kilometer', max_digits=10)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum base fare', max_digits=10)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage cut for the platform', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'system_configs',
            },
        ),
    ]
