# Generated by Django 6.0.6 on 2026-07-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0007_systemconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='base_fare',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='platform_fee_percentage',
        ),
    ]
