# Generated by Django 6.0.6 on 2026-07-01 22:30

import django.db.models.deletion
import sevy_app.models.trip
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0008_remove_systemconfig_base_fare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(default=sevy_app.models.trip.generate_trip_id, max_length=50, primary_key=True, serialize=False)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_time', models.CharField(help_text="e.g., '15 mins'", max_length=50)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('momo', 'Mobile Money')], default='cash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driverid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_trips', to='sevy_app.driver')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
