# Generated by Django 6.0.6 on 2026-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0010_trip_destination_lat_trip_destination_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
