# Generated by Django 6.0.6 on 2026-07-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0011_driver_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
