# Generated by Django 6.0.6 on 2026-07-02 17:46

import django.db.models.deletion
import sevy_app.models.transaction
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0012_trip_transaction_id_trip_trip_distance_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='transaction_id',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(default=sevy_app.models.transaction.generate_transaction_id, max_length=50, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('trip', 'Trip')], default='trip', max_length=50)),
                ('related_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RWF', max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='sevy_app.transaction'),
        ),
    ]
