# Generated by Django 6.0.6 on 2026-07-02 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0013_remove_trip_transaction_id_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driverid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
