# Generated by Django 6.0.6 on 2026-07-02 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0015_remove_driver_id_alter_driver_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driverid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_trips', to='sevy_app.driver'),
        ),
    ]
