# Generated by Django 6.0.6 on 2026-07-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0016_alter_trip_driverid'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='choose_driver_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Fee percentage charged to passenger for manually choosing a driver', max_digits=5),
        ),
    ]
