# Generated by Django 6.0.6 on 2026-07-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0017_systemconfig_choose_driver_fee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='service_type',
            field=models.CharField(choices=[('driver_and_car', 'Driver & Car'), ('driver_only', 'Driver Only')], default='driver_and_car', max_length=20),
        ),
    ]
