# Generated by Django 6.0.6 on 2026-07-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0018_trip_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='driver_only_cost_per_km',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Cost per kilometer for driver-only trips', max_digits=10),
        ),
    ]
