# Generated by Django 6.0.6 on 2026-07-02 20:35

import sevy_app.models.car
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0019_systemconfig_driver_only_cost_per_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(default=sevy_app.models.car.generate_car_id, max_length=50, primary_key=True, serialize=False)),
                ('companyid', models.CharField(help_text='ID of the company or owner', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_long', models.FloatField(blank=True, null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('capacity_seats', models.IntegerField(default=4)),
                ('engine_power', models.CharField(blank=True, help_text='e.g. 670 HP', max_length=100, null=True)),
                ('max_speed', models.CharField(blank=True, help_text='e.g. 250km/h', max_length=100, null=True)),
                ('fuel_range', models.CharField(blank=True, help_text='e.g. 405 Miles or Electric', max_length=100, null=True)),
                ('advanced_features', models.JSONField(default=list, help_text="Array of feature names e.g. ['Autopilot', 'Auto Parking']")),
                ('image', models.CharField(blank=True, help_text='URL or path to car image', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-created_at'],
            },
        ),
    ]
