# Generated by Django 6.0.6 on 2026-07-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0020_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
