# Generated by Django 6.0.6 on 2026-07-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0021_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.JSONField(default=list, help_text='Array of image paths or URLs'),
        ),
    ]
