# Generated by Django 6.0.6 on 2026-07-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0022_remove_car_image_car_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='likes',
            field=models.JSONField(default=list, help_text='Array of user IDs who liked this car'),
        ),
    ]
