# Generated by Django 6.0.6 on 2026-07-02 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0023_car_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='likes',
        ),
        migrations.CreateModel(
            name='CarLike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_likes', to='sevy_app.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car_likes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'car')},
            },
        ),
    ]
