# Generated by Django 6.0.6 on 2026-07-02 22:56

import django.db.models.deletion
import sevy_app.models.car_review
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0024_remove_car_likes_carlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('review_id', models.CharField(default=sevy_app.models.car_review.generate_review_id, max_length=50, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating from 1.0 to 5.0', max_digits=3)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sevy_app.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'car')},
            },
        ),
    ]
