# Generated by Django 6.0.6 on 2026-07-03 00:00

import sevy_app.models.company
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0025_carreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(default=sevy_app.models.company.generate_company_id, max_length=50, primary_key=True, serialize=False)),
                ('host_name', models.CharField(help_text='Name of the individual host/owner e.g. Hela Quintin', max_length=255)),
                ('company_name', models.CharField(blank=True, help_text='Optional name of the registered company', max_length=255, null=True)),
                ('profile_image', models.CharField(blank=True, help_text='URL or path to profile image', max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
