# Generated by Django 6.0.6 on 2026-07-03 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0026_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='companyid',
            field=models.ForeignKey(db_column='companyid', help_text='ID of the company or owner', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='sevy_app.company'),
        ),
    ]
