# Generated by Django 6.0.6 on 2026-07-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('coming', 'Coming'), ('arrived', 'Arrived')], max_length=20, null=True),
        ),
    ]
