# Generated by Django 6.0.6 on 2026-07-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0031_alter_trip_driver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready'), ('coming', 'Coming'), ('rejected', 'Rejected')], default='waiting', max_length=20),
        ),
    ]
