# Generated by Django 6.0.6 on 2026-07-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0032_alter_trip_driver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
