# Generated by Django 6.0.6 on 2026-07-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0033_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
