# Generated by Django 6.0.6 on 2026-07-04 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0036_company_location_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='companyid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_bookings', to='sevy_app.company'),
        ),
    ]
