# Generated by Django 6.0.6 on 2026-07-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0037_carbooking_companyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbooking',
            old_name='preferred_driver_gender',
            new_name='client_sex',
        ),
    ]
