# Generated by Django 6.0.6 on 2026-07-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0038_rename_preferred_driver_gender_carbooking_client_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='companyid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='sevy_app.company'),
        ),
    ]
