# Generated by Django 6.0.6 on 2026-07-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0040_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
