# Generated by Django 6.0.6 on 2026-07-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0041_car_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance', max_digits=12),
        ),
        migrations.AddField(
            model_name='company',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Accumulated bonuses', max_digits=12),
        ),
    ]
