# Generated by Django 6.0.6 on 2026-07-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0042_company_balance_company_bonuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for the company'),
        ),
    ]
