# Generated by Django 6.0.6 on 2026-07-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0043_company_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue generated by the platform', max_digits=15),
        ),
    ]
