# Generated by Django 6.0.6 on 2026-07-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0044_systemconfig_total_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('wait_approval', 'Wait Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='wait_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('trip', 'Trip'), ('withdrawal', 'Withdrawal')], default='trip', max_length=50),
        ),
    ]
