# Generated by Django 6.0.6 on 2026-07-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0046_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='platform_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=28.0, help_text='Percentage commission platform takes from bookings/trips', max_digits=5),
        ),
    ]
