# Generated by Django 6.0.6 on 2026-07-07 12:51

import django.db.models.deletion
import sevy_app.models.platform_commission
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0047_systemconfig_platform_commission_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('trip', 'Trip'), ('withdrawal', 'Withdrawal'), ('carbooking', 'Car Booking'), ('cartripbooking', 'Car Trip Booking'), ('platform_commission', 'Platform Commission')], default='trip', max_length=50),
        ),
        migrations.CreateModel(
            name='PlatformCommission',
            fields=[
                ('commission_id', models.CharField(default=sevy_app.models.platform_commission.generate_commission_id, max_length=50, primary_key=True, serialize=False)),
                ('source_type', models.CharField(help_text="e.g., 'carbooking', 'trip'", max_length=50)),
                ('related_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_earned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
