# Generated by Django 6.0.6 on 2026-07-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0048_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='companyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_bookings', to='sevy_app.company'),
        ),
    ]
