# Generated by Django 6.0.6 on 2026-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0049_alter_carbooking_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_approved',
            field=models.BooleanField(default=False, help_text='Set to True when customer approves the booking is completed'),
        ),
    ]
