# Generated by Django 6.0.6 on 2026-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0050_transaction_customer_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_bookings',
            field=models.IntegerField(default=0, help_text='Cached total number of bookings'),
        ),
        migrations.AddField(
            model_name='company',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cached total income', max_digits=12),
        ),
    ]
