# Generated by Django 6.0.6 on 2026-07-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0051_company_total_bookings_company_total_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='gross_income',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total volume of all transactions', max_digits=15),
        ),
    ]
