# Generated by Django 6.0.6 on 2026-07-07 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0052_systemconfig_gross_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcommission',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='sevy_app.transaction'),
        ),
    ]
