# Generated by Django 6.0.6 on 2026-07-09 17:44

import sevy_app.models.user_search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0053_platformcommission_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearch',
            name='id',
            field=models.CharField(default=sevy_app.models.user_search.generate_search_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='search_type',
            field=models.CharField(choices=[('place', 'Place')], default='place', max_length=50),
        ),
    ]
