# Generated by Django 6.0.6 on 2026-07-09 19:03

import django.db.models.deletion
import sevy_app.models.explore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0054_alter_usersearch_id_alter_usersearch_search_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreCategory',
            fields=[
                ('id', models.CharField(default=sevy_app.models.explore.generate_category_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'explorecategory',
            },
        ),
        migrations.AlterField(
            model_name='explore',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevy_app.explorecategory'),
        ),
    ]
