# Generated by Django 6.0.6 on 2026-07-09 19:31

import sevy_app.models.explore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0055_explorecategory_alter_explore_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='id',
            field=models.CharField(default=sevy_app.models.explore.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='explorecategory',
            name='id',
            field=models.CharField(default=sevy_app.models.explore.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
