# Generated by Django 6.0.6 on 2026-07-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0056_alter_explore_id_alter_explorecategory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
