# Generated by Django 6.0.6 on 2026-07-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0057_transaction_tracking_number_trip_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
