# Generated by Django 6.0.6 on 2026-07-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0058_driver_experience_years_driver_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
