# Generated by Django 6.0.6 on 2026-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0059_driver_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='driver_per_day_price',
            field=models.DecimalField(decimal_places=2, default=20000.0, help_text='Price for booking a driver per day', max_digits=10),
        ),
    ]
