# Generated by Django 6.0.6 on 2026-07-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0060_systemconfig_driver_per_day_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='booking_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
