# Generated by Django 6.0.6 on 2026-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0061_carbooking_booking_number_carbooking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='booking_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='id',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
