# Generated by Django 6.0.6 on 2026-07-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0063_car_company_user_link_carbooking_company_user_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='car',
            name='company_user_link',
        ),
    ]
