# Generated by Django 6.0.6 on 2026-07-12 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0064_rename_user_company_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='userid',
            field=models.OneToOneField(help_text='Links to auth User for password & login', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
