# Generated by Django 6.0.6 on 2026-07-12 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0065_remove_company_company_id_alter_company_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='userid',
        ),
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.OneToOneField(db_column='company_id', default='default', help_text='Links to auth User for password & login', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company_profile', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
