# Generated by Django 6.0.6 on 2026-07-12 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0065_remove_company_company_id_alter_company_userid'),
    ]

    operations = [
    ]
