# Generated by Django 6.0.6 on 2026-07-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0067_userinfo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='driver_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting for Driver'), ('accepted', 'Driver Accepted'), ('rejected', 'Driver Rejected')], max_length=20, null=True),
        ),
    ]
