# Generated by Django 6.0.6 on 2026-07-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0068_carbooking_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='approval_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('requestsent', 'Request Sent'), ('approved', 'Approved')], default='waiting', max_length=20),
        ),
    ]
