# Generated by Django 6.0.6 on 2026-07-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0069_trip_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='admin_approval_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('trip', 'Trip Alert'), ('rental', 'Rental Booking'), ('transaction', 'Payment Transaction'), ('system', 'System Broadcast'), ('promotional', 'Promotional'), ('trip_approval', 'Trip Approval')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='approval_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('requestsent', 'Request Sent'), ('approved', 'Approved'), ('denied', 'Denied')], default='waiting', max_length=20),
        ),
    ]
