# Generated by Django 6.0.6 on 2026-07-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0070_carbooking_admin_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner_id_url',
            field=models.CharField(blank=True, help_text='URL or path to owner ID or passport', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rdb_certificate_url',
            field=models.CharField(blank=True, help_text='URL or path to business registration certificate', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('trip', 'Trip Alert'), ('rental', 'Rental Booking'), ('transaction', 'Payment Transaction'), ('system', 'System Broadcast'), ('promotional', 'Promotional'), ('trip_approval', 'Trip Approval'), ('booking_cancelled', 'Booking Cancelled')], default='system', max_length=20),
        ),
    ]
