# Generated by Django 6.0.6 on 2026-07-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0071_company_owner_id_url_company_rdb_certificate_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text='Reason for cancellation/denial', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='True if the company registration was denied/cancelled'),
        ),
    ]
