# Generated by Django 6.0.6 on 2026-07-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0072_company_cancellation_reason_company_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('waitingapproval', 'Waiting Approval'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='waitingapproval', max_length=20),
        ),
    ]
