# Generated by Django 6.0.6 on 2026-07-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0073_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
