# Generated by Django 6.0.6 on 2026-07-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0074_platformcommission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
