# Generated by Django 6.0.6 on 2026-07-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0075_driver_cancellation_reason_driver_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('carrental', 'Car Rental'), ('tourism', 'Tourism')], default='carrental', help_text='Type of the company', max_length=20),
        ),
    ]
