# Generated by Django 6.0.6 on 2026-07-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0076_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fcmtokens',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
