# Generated by Django 6.0.6 on 2026-07-30 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0077_userinfo_device_type_userinfo_fcmtokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='fcmtokens',
        ),
        migrations.CreateModel(
            name='FCMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('fcm_token', models.TextField()),
                ('is_loggedin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fcmusers',
            },
        ),
    ]
