# Generated by Django 6.0.6 on 2026-07-30 21:56

import sevy_app.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0078_remove_userinfo_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmuser',
            name='id',
        ),
        migrations.AddField(
            model_name='fcmuser',
            name='custom_id',
            field=models.CharField(default=sevy_app.models.user.generate_custom_id, max_length=50, primary_key=True, serialize=False),
        ),
    ]
