# Generated by Django 6.0.6 on 2026-07-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0079_remove_fcmuser_id_fcmuser_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='plate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_make_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
