# Generated by Django 6.0.6 on 2026-08-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0080_alter_driver_plate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='customer_approval_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('trip', 'Trip Alert'), ('rental', 'Rental Booking'), ('transaction', 'Payment Transaction'), ('system', 'System Broadcast'), ('promotional', 'Promotional'), ('trip_approval', 'Trip Approval'), ('booking_cancelled', 'Booking Cancelled')], default='system', max_length=50),
        ),
    ]
