# Generated by Django 6.0.6 on 2026-08-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0081_carbooking_customer_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='company_customer_approval',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('requestsent', 'Request Sent'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='driver_customer_approval',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('requestsent', 'Request Sent'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='customer_approval_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('requestsent', 'Request Sent'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
