# Generated by Django 6.0.6 on 2026-08-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0082_carbooking_company_customer_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='admin_approval_status',
        ),
        migrations.AddField(
            model_name='carbooking',
            name='adminapprovalfor',
            field=models.CharField(choices=[('none', 'None'), ('driver', 'Driver'), ('company', 'Company'), ('both', 'Both')], default='none', max_length=20),
        ),
    ]
