# Generated by Django 6.0.6 on 2026-08-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0083_remove_carbooking_admin_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='adminapprovalfor',
        ),
        migrations.AddField(
            model_name='carbooking',
            name='admin_company_approval',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('requestsent', 'Request Sent'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='admin_driver_approval',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('requestsent', 'Request Sent'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
