# Generated by Django 6.0.6 on 2026-08-30 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0084_remove_carbooking_adminapprovalfor_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='company',
        #     name='userid',
        # ),
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.OneToOneField(db_column='company_id', help_text='Links to auth User for password & login', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
