# Generated by Django 6.0.6 on 2026-08-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0085_remove_company_userid_trip_start_time_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='company',
                    name='userid',
                ),
            ],
            database_operations=[]
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('instanttrip', 'Instant Trip'), ('scheduledtrip', 'Scheduled Trip')], default='instanttrip', max_length=20),
        ),
    ]
