# Generated by Django 6.0.6 on 2026-09-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0087_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='owns_car',
            field=models.BooleanField(default=False),
        ),
    ]
