# Generated by Django 6.0.6 on 2026-09-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevy_app', '0088_driver_owns_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='app_version',
            field=models.CharField(default='1.0.0', help_text='Current mobile app version', max_length=50),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='release_notes',
            field=models.TextField(blank=True, help_text='Release notes for the current version', null=True),
        ),
    ]
